### PR TITLE
Update scanners list to include mobile options

### PR DESCRIPTION
**Pull request by hannahswain**
Added a section for mobile phones and added new columns that are relevant to these apps. Added my suggestion.

### CODE REVIEW

**Comment by danielquinn** [comment]
Hi Hannah!  Thanks for your contribution :-)  I assume you're recommending this scanner because you've used it yourself with Paperless?  It's funny, I never considered phone-based scanners when this project started.

**Review by danielquinn — APPROVED** [review]
👍🏻

**Comment by hannahswain** [comment]
Yes, this is what I've been using rather than pulling out a scanner whenever I need to add documents. It's great because it'll also let you set up naming conventions, so I have a fill in field for correspondent, title, and tags. It'll then correctly name the document for Paperless to guess the correct values. I save it to a local folder on Android. SyncThing picks it up and moves it to the consume folder for me. So easy and then I don't end up with a backlog of stuff to scan.

**Review by kohfuchs — APPROVED** [review]
doing the same here, good idea to add it to the project.

**Review by kohfuchs — APPROVED** [review]

**Review by Sblop — APPROVED** [review]

**Review by MasterofJOKers — APPROVED** [review]

**Pull request merged**
