### PR TITLE
* Docs: Add web interface screenshots

### PR DESCRIPTION
**Pull request by bmsleight**

### CODE REVIEW

**Comment by MasterofJOKers** [comment]
Did you forget the `screenshots.rst` here?

**Comment by bmsleight** [comment]
@MasterofJOKers Thanks! now added

**Comment by bmsleight** [comment]
@pitkley 
Not confidential. Example documents in public domain already. Including with my name.
GDPR, no issues for me. 
 It is good to make sure. :)

**Comment by ovv** [comment]
@bmsleight could you do a push to the branch to re-trigger a travis build (See #511 #512) as we can't merge this PR for the moment

**Comment by pitkley** [comment]
I am going to close and reopen this PR, since that [seems to fix Travis](https://github.com/the-paperless-project/paperless/issues/512#issuecomment-469050805) (thanks for discovering this easy fix, @stgarf 👍).

**Pull request merged**
